# Generated by Django 4.1 on 2022-09-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, verbose_name="имя пользователя"),
                ),
                ("password", models.CharField(max_length=200, verbose_name="пароль")),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=50, verbose_name="имя"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="фамилия"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=12, verbose_name="телефон"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=30, verbose_name="город"),
                ),
                (
                    "verification_flag",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="флаг верификации",
                    ),
                ),
                (
                    "number_of_posted_news",
                    models.IntegerField(
                        default=0, verbose_name="количество опубликованных новостей"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, verbose_name="дата рождения"),
                ),
            ],
        ),
    ]
