# Generated by Django 4.1 on 2022-09-21 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=12, verbose_name="телефон"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=30, verbose_name="город"),
                ),
                (
                    "verification_flag",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="флаг верификации",
                    ),
                ),
                (
                    "number_of_posted_news",
                    models.IntegerField(
                        default=0, verbose_name="количество опубликованных новостей"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(blank=True, verbose_name="дата рождения"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
