# Generated by Django 4.1 on 2022-09-21 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_profile_delete_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": (("can_post_news", "Может публиковать новости"),),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.RemoveField(
            model_name="profile",
            name="verification_flag",
        ),
    ]
