# Generated by Django 4.1 on 2022-09-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0003_alter_profile_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": (
                    ("can_post_news", "Может публиковать новости"),
                    ("can_verify", "Может верифицировать"),
                ),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_mark",
            field=models.BooleanField(default=False, verbose_name="Верификация"),
        ),
    ]
