# Generated by Django 4.1 on 2022-09-20 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="заголовок"
                    ),
                ),
                (
                    "content",
                    models.TextField(max_length=10000, verbose_name="текст новости"),
                ),
                (
                    "creation_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="статус")),
            ],
            options={
                "ordering": ["creation_at"],
            },
        ),
        migrations.CreateModel(
            name="Commentaries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        default="anonim",
                        max_length=200,
                        verbose_name="имя пользователя",
                    ),
                ),
                (
                    "commentary",
                    models.CharField(max_length=500, verbose_name="комментарий"),
                ),
                (
                    "connected_news",
                    models.ForeignKey(
                        default="Такой новости нет",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="news_board.news",
                        verbose_name="имя новости",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="имя зарегистрированого пользователя",
                    ),
                ),
            ],
        ),
    ]
